#!/usr/bin/env node

import { Client as McpClient } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { serverCwd } from "./shared.js";

const client = new McpClient({
  name: "Echo",
  version: "1.0.0",
});

/**
 * An instance of StdioClientTransport used to establish communication with a child process.
 * The transport is configured to execute a Node.js command that runs a script located at './dist/stdio.js'.
 * The working directory for the spawned process is set to the value of the serverCwd variable.
 * This transport facilitates standard input/output based interaction with the child process.
 */
const transport = new StdioClientTransport({
  command: "node",
  args: ["./dist/stdio.js"],
  cwd: serverCwd,
});
await client.connect(transport);

/**
 * Represents a collection of prompts retrieved from the client.
 * This variable stores the result of an asynchronous operation that fetches
 * available prompts from the client service.
 * @type {Promise<Array>}
 */
const prompts = await client.listPrompts();

console.dir(prompts, { depth: null });

/**
 * Represents the result of a prompt execution.
 * Contains the output or response generated by the prompt.
 * @type {Promise<any>}
 */
const result = await client.getPrompt({
  name: "Echo",
  arguments: {
    message: "Hello, world!",
  },
});

console.dir(result, { depth: null });

await transport.close();
